version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/aws-nodejs-express-ec2
hook:
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: ec2-user
  AfterStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: ec2-user
